// web-vue/src/views/Home.vue
<template>
  <div :class="['home-wrap', { dark: settings.darkMode }]">
    <div v-if="accounts.length === 0" class="empty">
      <p>暂无账户</p>
      <p style="font-size:13px;margin-top:8px;color:#bbb;">点击上方 + 添加账户</p>
    </div>

    <div v-for="acc in accounts" :key="acc.id" class="card-wrap">
      <div class="card" :class="settings.cardSize" :style="cardStyle(acc)">
        <!-- Status bar -->
        <div class="status-bar" :style="{ background: quotaColor(acc), height: refreshing ? '6px' : '4px' }" />

        <div class="card-content">
          <!-- Header: avatar + username + percent badge -->
          <div class="card-header-row">
            <div class="user-info">
              <div class="avatar" :style="{ background: quotaColor(acc) + '20', color: quotaColor(acc) }">
                {{ acc.username.charAt(0).toUpperCase() }}
              </div>
              <div>
                <div class="username">{{ acc.username }}</div>
                <div class="plan-info" v-if="data[acc.id]?.planName">
                  {{ data[acc.id].planName }}
                  <span v-if="data[acc.id]?.days_remaining != null" :style="{ color: daysColor(acc) }">
                    · 剩余 {{ data[acc.id].days_remaining }} 天
                  </span>
                </div>
              </div>
            </div>

            <div v-if="data[acc.id]" class="percent-badge" :style="{ background: quotaColor(acc) + '15', color: quotaColor(acc) }">
              {{ percent(acc).toFixed(1) }}%
            </div>
            <div v-else-if="data[acc.id]?.loading" class="percent-badge loading-badge">
              加载中
            </div>
          </div>

          <!-- Error -->
          <div v-if="data[acc.id]?.error" class="error-msg">{{ data[acc.id].error }}</div>

          <!-- Quota info -->
          <template v-else-if="data[acc.id]">
            <div class="quota-row">
              <div class="quota-item">
                <div class="quota-label">已用额度</div>
                <div class="quota-value">{{ data[acc.id].amountUsed?.toFixed(1) }}</div>
              </div>
              <div class="quota-item">
                <div class="quota-label">总额度</div>
                <div class="quota-value">{{ data[acc.id].amount?.toFixed(1) }}</div>
              </div>
              <div class="quota-item text-right">
                <div class="quota-label">剩余额度</div>
                <div class="quota-value" :style="{ color: quotaColor(acc) }">{{ data[acc.id].remaining?.toFixed(1) }}</div>
              </div>
            </div>

            <!-- Progress bar -->
            <div class="progress-track">
              <div class="progress-fill" :style="{ width: Math.min(100, percent(acc)) + '%', background: quotaColor(acc) }" />
            </div>

            <!-- Countdown to reset -->
            <div class="countdown-row" v-if="data[acc.id]?.nextResetTime">
              距重置: <span class="countdown-value">{{ getCountdown(data[acc.id].nextResetTime) }}</span>
            </div>
          </template>

          <!-- Actions -->
          <div class="actions-row">
            <button @click="refreshAccount(acc)" :disabled="refreshing">
              {{ refreshing ? '刷新中' : '刷新' }}
            </button>
            <button @click="$emit('edit', acc)">编辑</button>
            <button @click="deleteAccount(acc.id)" class="delete-btn">删除</button>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { inject, ref, onMounted, onUnmounted } from 'vue';
import { useSettings } from '../stores/settings.js';

defineEmits(['edit']);

const { settings } = useSettings();
const accounts = inject('accounts');
const accountData = inject('accountData');
const refreshAll = inject('refreshAll');
const deleteAccount = inject('deleteAccount');

const data = accountData;
const refreshing = ref(false);
const tick = ref(0);
let timer = null;

onMounted(() => {
  timer = setInterval(() => { tick.value++; }, 1000);
});

onUnmounted(() => {
  if (timer) clearInterval(timer);
});

function refreshAccount(acc) {
  refreshing.value = true;
  refreshAll().finally(() => {
    setTimeout(() => { refreshing.value = false; }, 500);
  });
}

function percent(acc) {
  const d = data[acc.id];
  if (!d || !d.amount) return 0;
  return Math.min(100, (d.amountUsed / d.amount) * 100);
}

function quotaColor(acc) {
  const p = percent(acc);
  if (refreshing.value) return '#9E9E9E';
  if (p > 50) return '#4CAF50';
  if (p > 20) return '#FFC107';
  return '#F44336';
}

function daysColor(acc) {
  const d = data[acc.id];
  if (!d) return '#9E9E9E';
  if (d.days_remaining > 10) return '#4CAF50';
  if (d.days_remaining > 3) return '#FFC107';
  return '#F44336';
}

function cardStyle(acc) {
  return { '--quota-color': quotaColor(acc) };
}

function getCountdown(resetTime) {
  // Access tick to make reactive
  const _ = tick.value;
  if (!resetTime) return '';
  try {
    const sdf = new Date(resetTime.replace(/\//g, '/'));
    const diff = sdf.getTime() - Date.now();
    if (diff <= 0) return '已重置';
    const h = Math.floor(diff / (1000 * 60 * 60));
    const m = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
    const s = Math.floor((diff % (1000 * 60)) / 1000);
    return `${h}小时${m}分${s}秒`;
  } catch {
    return '';
  }
}
</script>

<style scoped>
.home-wrap {
  background: #f5f5f5;
  min-height: 100vh;
  padding: 12px 0;
}
.home-wrap.dark {
  background: #1a1a1a;
}
.card-wrap {
  max-width: 480px;
  margin: 0 auto;
  padding: 0 16px;
}
.card {
  background: #fff;
  border-radius: 12px;
  margin-bottom: 12px;
  box-shadow: 0 1px 3px rgba(0,0,0,0.08);
  overflow: hidden;
}
.card.small { padding: 12px; }
.card.medium { padding: 16px; }
.card.large { padding: 20px; }
.dark .card { background: #2a2a2a; }
.status-bar {
  margin: -12px -16px 0 -16px;
  height: 4px;
  transition: height 0.2s;
}
.card.small .status-bar { margin: -12px -12px 0 -12px; }
.card.large .status-bar { margin: -20px -20px 0 -20px; }
.card-content { padding: 0 4px; }
.card-header-row {
  display: flex;
  justify-content: space-between;
  align-items: center;
  margin-top: 12px;
}
.user-info { display: flex; align-items: center; gap: 12px; }
.avatar {
  width: 40px;
  height: 40px;
  border-radius: 50%;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: bold;
  font-size: 18px;
}
.username { font-weight: bold; font-size: 16px; }
.plan-info { font-size: 12px; color: #888; margin-top: 2px; }
.percent-badge {
  padding: 6px 12px;
  border-radius: 8px;
  font-weight: bold;
  font-size: 15px;
}
.loading-badge { background: #9E9E9E15; color: #9E9E9E; font-size: 12px; font-weight: normal; }
.error-msg { color: #F44336; font-size: 13px; margin-top: 8px; }
.quota-row {
  display: flex;
  justify-content: space-between;
  font-size: 13px;
  margin-top: 12px;
}
.quota-item { text-align: left; }
.quota-item.text-right { text-align: right; }
.quota-label { color: #888; font-size: 12px; }
.quota-value { font-weight: bold; margin-top: 2px; }
.progress-track {
  height: 8px;
  background: #eee;
  border-radius: 4px;
  margin-top: 12px;
  overflow: hidden;
}
.dark .progress-track { background: #333; }
.progress-fill {
  height: 100%;
  border-radius: 4px;
  transition: width 0.3s;
}
.countdown-row {
  font-size: 12px;
  color: #888;
  margin-top: 8px;
}
.countdown-value { color: #1976D2; }
.actions-row {
  display: flex;
  gap: 8px;
  justify-content: flex-end;
  margin-top: 12px;
}
.actions-row button {
  background: none;
  border: 1px solid #ddd;
  border-radius: 6px;
  padding: 4px 10px;
  cursor: pointer;
  font-size: 12px;
}
.dark .actions-row button { border-color: #444; color: #e0e0e0; }
.actions-row .delete-btn { color: #F44336; }
.empty { text-align: center; padding: 60px 20px; color: #999; font-size: 15px; }
</style>

// web-react/src/pages/Home.jsx
import { useState, useEffect, useRef } from 'react';
import { useAccounts } from '../stores/useAccounts.jsx';
import { useSettings } from '../stores/useSettings.jsx';

export default function Home({ onEdit }) {
  const { accounts, accountData, refreshAll, deleteAccount } = useAccounts();
  const { settings } = useSettings();
  const [refreshing, setRefreshing] = useState(false);

  useEffect(() => {
    if (accounts.length > 0 && Object.keys(accountData).length === 0) {
      refreshAll();
    }
  }, []);

  async function handleRefresh() {
    setRefreshing(true);
    await refreshAll();
    setRefreshing(false);
  }

  const bg = settings.darkMode ? '#1a1a1a' : '#f5f5f5';
  const textColor = settings.darkMode ? '#e0e0e0' : '#333';
  const metaColor = settings.darkMode ? '#888' : '#888';

  // Card size styles
  const cardSizes = {
    small: { padding: '12px', gap: '6px', fontSize: '12px', spacing: '8px' },
    medium: { padding: '16px', gap: '8px', fontSize: '13px', spacing: '12px' },
    large: { padding: '20px', gap: '10px', fontSize: '14px', spacing: '16px' },
  };
  const sz = cardSizes[settings.cardSize] || cardSizes.medium;

  if (accounts.length === 0) {
    return (
      <div style={{ textAlign: 'center', padding: '60px 20px', color: '#999', fontSize: '15px' }}>
        <p>暂无账户</p>
        <p style={{ fontSize: '13px', marginTop: '8px', color: '#bbb' }}>点击上方 + 添加账户</p>
      </div>
    );
  }

  return (
    <div style={{ background: bg, minHeight: '100vh', padding: `${sz.spacing} 0` }}>
      {accounts.map(acc => {
        const d = accountData[acc.id];
        return (
          <div key={acc.id} style={cardWrapStyle}>
            <AccountCard
              acc={acc}
              d={d}
              refreshing={refreshing}
              settings={settings}
              onRefresh={handleRefresh}
              onEdit={() => onEdit(acc)}
              onDelete={() => deleteAccount(acc.id)}
              sz={sz}
            />
          </div>
        );
      })}
    </div>
  );
}

function AccountCard({ acc, d, refreshing, settings, onRefresh, onEdit, onDelete, sz }) {
  const textColor = settings.darkMode ? '#e0e0e0' : '#333';
  const metaColor = settings.darkMode ? '#888' : '#888';
  const cardBg = settings.darkMode ? '#2a2a2a' : '#fff';
  const borderColor = settings.darkMode ? '#333' : '#eee';

  const remainingPercent = d ? (d.remaining / d.amount * 100) : 0;
  const isLoading = !d && !d?.error;

  // Quota color based on remaining percentage
  const quotaColor = refreshing ? '#9E9E9E'
    : remainingPercent > 50 ? '#4CAF50'
    : remainingPercent > 20 ? '#FFC107'
    : '#F44336';

  // Days color
  const daysColor = d?.days_remaining > 10 ? '#4CAF50'
    : d?.days_remaining > 3 ? '#FFC107'
    : '#F44336';

  return (
    <div style={{ ...cardStyle, background: cardBg, padding: sz.padding }}>
      {/* Status bar */}
      <div style={{
        height: refreshing ? '6px' : '4px',
        borderRadius: '4px 4px 0 0',
        margin: `-${sz.padding} -${sz.padding} 0 -${sz.padding}`,
        background: quotaColor,
        overflow: 'hidden',
      }}>
        {refreshing && <div style={loadingBarStyle(quotaColor)} />}
      </div>

      <div style={{ padding: '0 4px' }}>
        {/* Header: avatar + username + percent badge */}
        <div style={headerRowStyle}>
          <div style={userInfoStyle}>
            <div style={{ ...avatarStyle, background: quotaColor + '20', color: quotaColor }}>
              {acc.username.charAt(0).toUpperCase()}
            </div>
            <div>
              <div style={{ ...usernameStyle, color: textColor, fontSize: sz.fontSize }}>{acc.username}</div>
              {d?.planName && (
                <div style={{ fontSize: `${parseInt(sz.fontSize) - 2}px`, color: metaColor }}>
                  {d.planName}
                  {d.days_remaining != null && (
                    <span style={{ color: daysColor, marginLeft: '4px' }}>· 剩余 {d.days_remaining} 天</span>
                  )}
                </div>
              )}
            </div>
          </div>

          {d ? (
            <div style={{ ...percentBadgeStyle, background: quotaColor + '15', color: quotaColor }}>
              {remainingPercent.toFixed(1)}%
            </div>
          ) : isLoading ? (
            <div style={{ ...percentBadgeStyle, background: '#9E9E9E15', color: '#9E9E9E' }}>
              <span style={loadingDotsStyle}>加载中</span>
            </div>
          ) : null}
        </div>

        {/* Error */}
        {d?.error && (
          <div style={errorStyle}>{d.error}</div>
        )}

        {/* Quota info */}
        {d && !d.error && (
          <>
            <div style={{ ...quotaRowStyle, fontSize: sz.fontSize, marginTop: sz.gap }}>
              <div style={quotaItemStyle}>
                <div style={{ color: metaColor }}>已用额度</div>
                <div style={{ fontWeight: 'bold', color: textColor }}>{d.amountUsed?.toFixed(1)}</div>
              </div>
              <div style={quotaItemStyle}>
                <div style={{ color: metaColor }}>总额度</div>
                <div style={{ fontWeight: 'bold', color: textColor }}>{d.amount?.toFixed(1)}</div>
              </div>
              <div style={{ ...quotaItemStyle, textAlign: 'right' }}>
                <div style={{ color: metaColor }}>剩余额度</div>
                <div style={{ fontWeight: 'bold', color: quotaColor }}>{d.remaining?.toFixed(1)}</div>
              </div>
            </div>

            {/* Progress bar */}
            <div style={{ ...progressTrackStyle, background: settings.darkMode ? '#333' : '#eee', marginTop: sz.gap }}>
              <div style={{
                ...progressFillStyle,
                width: `${Math.min(100, remainingPercent)}%`,
                background: quotaColor
              }} />
            </div>

            {/* Footer: update time + countdown */}
            <div style={{ ...footerRowStyle, marginTop: sz.gap }}>
              <CountdownTimer resetTime={d.nextResetTime} darkMode={settings.darkMode} />
            </div>
          </>
        )}

        {/* Actions */}
        <div style={actionsRowStyle}>
          <button
            style={{ ...btnStyle, borderColor, color: textColor, fontSize: `${parseInt(sz.fontSize) - 1}px` }}
            onClick={onRefresh}
            disabled={refreshing}
          >
            {refreshing ? '刷新中' : '刷新'}
          </button>
          <button
            style={{ ...btnStyle, borderColor, color: textColor, fontSize: `${parseInt(sz.fontSize) - 1}px` }}
            onClick={onEdit}
          >
            编辑
          </button>
          <button
            style={{ ...btnStyle, borderColor, color: '#F44336', fontSize: `${parseInt(sz.fontSize) - 1}px` }}
            onClick={onDelete}
          >
            删除
          </button>
        </div>
      </div>
    </div>
  );
}

function CountdownTimer({ resetTime, darkMode }) {
  const [countdown, setCountdown] = useState('');
  const textColor = darkMode ? '#888' : '#888';

  useEffect(() => {
    if (!resetTime) {
      setCountdown('');
      return;
    }

    function calculate() {
      try {
        const sdf = new Date(resetTime.replace(/\//g, '/'));
        const diff = sdf.getTime() - Date.now();
        if (diff <= 0) {
          setCountdown('已重置');
          return;
        }
        const h = Math.floor(diff / (1000 * 60 * 60));
        const m = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));
        const s = Math.floor((diff % (1000 * 60)) / 1000);
        setCountdown(`${h}小时${m}分${s}秒`);
      } catch {
        setCountdown('');
      }
    }

    calculate();
    const timer = setInterval(calculate, 1000);
    return () => clearInterval(timer);
  }, [resetTime]);

  if (!countdown) return null;

  return (
    <div style={{ fontSize: '12px', color: textColor }}>
      距重置: <span style={{ color: '#1976D2' }}>{countdown}</span>
    </div>
  );
}

const cardWrapStyle = {
  maxWidth: '480px',
  margin: '0 auto',
  padding: '0 16px',
};

const cardStyle = {
  borderRadius: '12px',
  boxShadow: '0 1px 3px rgba(0,0,0,0.08)',
  marginBottom: '12px',
  overflow: 'hidden',
};

const headerRowStyle = {
  display: 'flex',
  justifyContent: 'space-between',
  alignItems: 'center',
  marginTop: '12px',
};

const userInfoStyle = {
  display: 'flex',
  alignItems: 'center',
  gap: '12px',
};

const avatarStyle = {
  width: '40px',
  height: '40px',
  borderRadius: '50%',
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'center',
  fontWeight: 'bold',
  fontSize: '18px',
};

const usernameStyle = {
  fontWeight: 'bold',
  fontSize: '16px',
};

const percentBadgeStyle = {
  padding: '6px 12px',
  borderRadius: '8px',
  fontWeight: 'bold',
  fontSize: '15px',
};

const loadingDotsStyle = {
  fontSize: '12px',
  fontWeight: 'normal',
};

const quotaRowStyle = {
  display: 'flex',
  justifyContent: 'space-between',
};

const quotaItemStyle = {
  textAlign: 'left',
};

const progressTrackStyle = {
  height: '8px',
  borderRadius: '4px',
  overflow: 'hidden',
};

const progressFillStyle = {
  height: '100%',
  borderRadius: '4px',
  transition: 'width 0.3s',
};

const footerRowStyle = {
  display: 'flex',
  justifyContent: 'space-between',
  alignItems: 'center',
};

const errorStyle = {
  color: '#F44336',
  fontSize: '13px',
  marginTop: '8px',
};

const actionsRowStyle = {
  display: 'flex',
  gap: '8px',
  justifyContent: 'flex-end',
  marginTop: '12px',
};

const btnStyle = {
  background: 'none',
  border: '1px solid #ddd',
  borderRadius: '6px',
  padding: '4px 10px',
  cursor: 'pointer',
  fontSize: '12px',
};

function loadingBarStyle(color) {
  return {
    height: '100%',
    background: `linear-gradient(90deg, ${color}40 0%, ${color} 50%, ${color}40 100%)`,
    backgroundSize: '200% 100%',
    animation: 'loading 1.5s ease-in-out infinite',
  };
}
